ARG VER_APP=2.0.3
ARG VER_NGX="1.21.6-alpine"

FROM --platform=$BUILDPLATFORM doocs/md:$VER_APP-assets AS assets
FROM --platform=$TARGETPLATFORM nginx:${VER_NGX}
LABEL MAINTAINER="ylb<contact@yanglibin.info>"
COPY --from=assets /app /usr/share/nginx/html
