ARG VER_APP=2.0.4
FROM --platform=$BUILDPLATFORM "doocs/md:$VER_APP-assets" AS assets

# detail https://github.com/lipanski/docker-static-website/blob/master/Dockerfile
FROM --platform=$TARGETPLATFORM lipanski/docker-static-website

WORKDIR /home/static

COPY --from=assets /app/assets /home/static

EXPOSE 80

CMD ["/busybox-httpd", "-f", "-v", "-p", "80", "-c", "httpd.conf"]
