ARG VER_APP=1.5.9
ARG VER_NGX=1.21.6-alpine

FROM "doocs/md:$VER_APP-assets" AS Assets
FROM "nginx:$VER_NGX"
LABEL MAINTAINER yanglbme<contact@yanglibin.info>
COPY --from=Assets /app/* /usr/share/nginx/html