ARG VER_APP=1.5.7
ARG VER_GOLANG=1.17.6-alpine3.15
ARG VER_ALPINE=3.15

FROM "doocs/md:$VER_APP-assets" AS Assets

FROM "golang:$VER_GOLANG" AS GoBuilder
COPY --from=Assets /app/dist /app/assets
COPY server/main.go /app
RUN apk add git bash gcc musl-dev upx
WORKDIR /app
RUN go build -ldflags "-w -s" -o md main.go && \
    apk add upx && \
    upx -9 -o md.minify md

FROM "alpine:$VER_ALPINE"
LABEL MAINTAINER soulteary<soulteary@gmail.com>
COPY --from=GoBuilder /app/md.minify /bin/md
CMD ["md"]