name: Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      versions:
        description: '要构建的版本（空格分隔，如: 2.1.0 latest）留空则构建最新3个版本+latest'
        required: false
        type: string
        default: ''

concurrency:
  group: docker-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push multi-arch images
      env:
        BUILD_VERSIONS: ${{ github.event.inputs.versions }}
      run: |
        chmod +x scripts/build-multiarch.sh
        bash scripts/build-multiarch.sh